"""add phone number

Revision ID: ab1bd9451056
Revises: 404bcec32d67
Create Date: 2022-01-30 22:07:29.316863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1bd9451056'
down_revision = '404bcec32d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
